# Autogenerated wrapper script for SDL2_jll for x86_64-linux-gnu
export libsdl2

using X11_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"

# Relative path to `libsdl2`
const libsdl2_splitpath = ["lib", "libSDL2.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libsdl2_path = ""

# libsdl2-specific global declaration
# This will be filled out by __init__()
libsdl2_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libsdl2 = "libSDL2-2.0.so.0"


"""
Open all libraries
"""
function __init__()
    global prefix = abspath(joinpath(@__DIR__, ".."))

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    append!.(Ref(PATH_list), (X11_jll.PATH_list,))
    append!.(Ref(LIBPATH_list), (X11_jll.LIBPATH_list,))

    global libsdl2_path = abspath(joinpath(artifact"SDL2", libsdl2_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libsdl2_handle = dlopen(libsdl2_path)
    push!(LIBPATH_list, dirname(libsdl2_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

